export type FaqItem = { question: string; answer: string };

export const faqs: FaqItem[] = [
  {
    question: "What is a professional EMF assessment?",
    answer:
      "A White Glove EMF assessment is a comprehensive, room-by-room evaluation of your home using calibrated professional instruments. We measure all four categories of EMF — radiofrequency (RF) radiation, AC magnetic fields, AC electric fields, and dirty electricity — and compare every reading against Building Biology guidelines. You receive a written report with prioritized recommendations.",
  },
  {
    question: "How long does an assessment take?",
    answer:
      "A typical single-family home takes 2.5 to 4 hours. Larger or multi-story homes, or those with complex environments (solar systems, multiple smart meters, nearby cell infrastructure) can take longer. We measure at sleeping positions, seating areas, and high-use zones, explaining findings as we go.",
  },
  {
    question: "What areas of Southwest Florida do you serve?",
    answer:
      "We serve Naples, Marco Island, Bonita Springs, Estero, Fort Myers, Cape Coral, and surrounding communities throughout Collier and Lee counties. We also travel for assessments in Sarasota and Charlotte counties — contact us to confirm availability for your location.",
  },
  {
    question: "Is EMF assessment based on real science?",
    answer:
      "Yes. We use calibrated meters and reference internationally recognized Building Biology guidelines. Our approach is measurement-first and data-driven — we report exactly what we find and rank it by significance, without fear marketing or exaggeration.",
  },
  {
    question: "Do I need to prepare anything before the visit?",
    answer:
      "Keep your home in its normal operating state. Leave WiFi routers, appliances, and smart devices powered on as usual, and do not move furniture or unplug devices beforehand — the goal is to measure your everyday exposure. Note any symptoms (sleep disruption, headaches, fatigue) and where they occur.",
  },
  {
    question: "What happens after the assessment?",
    answer:
      "You receive a written report within 48 hours detailing every measurement, the corresponding guideline, and a prioritized list of recommended actions ranked by health impact and cost-effectiveness — from free behavioral changes to professional shielding installations.",
  },
  {
    question: "Can you also perform the shielding installation?",
    answer:
      "Yes. We provide end-to-end service: assessment, shielding design, installation, and verification. We install RF-blocking films, shielding paint, metalized fabric panels, dirty electricity filters, demand switches, and medical-grade grounding systems — all with before-and-after measurements.",
  },
  {
    question: "What is dirty electricity and why does it matter?",
    answer:
      "Dirty electricity refers to high-frequency voltage transients riding on your home's standard 60 Hz power, often generated by LED drivers, solar inverters, dimmer switches, and switching power supplies. It can radiate into living spaces and is one of the most overlooked — and most correctable — EMF sources.",
  },
  {
    question: "Are smart meters a real concern?",
    answer:
      "Smart meters transmit data wirelessly far more frequently than most homeowners realize. A meter on an exterior wall adjacent to a bedroom or nursery deserves measurement. We document the actual RF output and help you understand opt-out and shielding options.",
  },
  {
    question: "How close is too close to a cell tower?",
    answer:
      "RF exposure follows an inverse-square relationship, so proximity and line-of-sight matter most. Homes within 500 meters of a macro tower or 100 meters of a 5G small cell, especially with upper-floor windows facing the tower, should prioritize measurement.",
  },
  {
    question: "What is medical-grade grounding?",
    answer:
      "Grounding (earthing) connects the body to the Earth's natural charge through a conductive mat, sheet, or patch tied to a verified ground. Clinical studies have shown reductions in cortisol and improvements in sleep. We install and verify systems against the outlet ground reference with body-voltage measurements.",
  },
  {
    question: "Will shielding affect my WiFi or cell signal?",
    answer:
      "Targeted shielding is designed to reduce exposure where it matters most — typically sleeping areas — while preserving usable connectivity elsewhere. We measure before and after so you can confirm both the reduction and that your home remains functional.",
  },
  {
    question: "Is this relevant if I'm building or renovating?",
    answer:
      "Absolutely. Building or renovating is the ideal time to address EMF — wiring layout, panel placement, and shielding can be designed in proactively, often at far lower cost than retrofitting later. We consult with homeowners, builders, and architects.",
  },
  {
    question: "Do you work with people who are electrically sensitive?",
    answer:
      "Yes. We work compassionately and methodically with electrically sensitive individuals, focusing on the sleeping environment first and verifying every change with measurements so improvements are objective and documented.",
  },
  {
    question: "How much does an assessment cost?",
    answer:
      "Pricing depends on home size and complexity. We provide a clear quote up front with no obligation. Many clients find the assessment alone delivers immediate, actionable value regardless of whether shielding is needed.",
  },
  {
    question: "How do I schedule?",
    answer:
      "Call us at 239-375-7090 or submit the contact form on this site. We confirm your address, discuss your primary concerns, and schedule a convenient time — same-week availability throughout Naples and Southwest Florida.",
  },
];
